CC=clang++
CFLAGS=-std=c++17
DEBUG_FLAGS=-O0 -g
RELEASE_FLAGS=-O3

SOURCE_DIR=./source
OUTPUT_DIR=./output
INCLUDE_DIR=$(SOURCE_DIR)/include
LIBRARY_DIR=$(SOURCE_DIR)/library

SOURCE=$(SOURCE_DIR)/main.cpp
OUTPUT=$(OUTPUT_DIR)/DupIm
LIBRARIES=-lpHash

debug:
	$(CC) $(SOURCE) $(CFLAGS) $(DEBUG_FLAGS) -I$(INCLUDE_DIR) -L$(LIBRARY_DIR) $(LIBRARIES) -o$(OUTPUT)

release:
	$(CC) $(SOURCE) $(CFLAGS) $(RELEASE_FLAGS) -I$(INCLUDE_DIR) -L$(LIBRARY_DIR) $(LIBRARIES) -o$(OUTPUT)
